HelloWorld/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path("admin/", admin.site.urls),
    path('hello/', include("hello.urls")),
    path('newyear/', include("newyear.urls")),
    path('tasks/', include("tasks.urls"))
]

hello/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("<str:name>", views.greet, name="greet"),
    path("Frontp", views.FrontP, name="index"),
    path("Home", views.Home, name = "Home")
]

newyear/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
]

tasks/urls.py
from django.urls import path

from . import views

app_name ="tasks"
urlpatterns = [
    path("", views.index, name="index"),
     path("add", views.add, name="add")
]

tasks/models.py
from django.db import models

# Create your models here.

hello/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, "hello/index.html")

def Home(request):
    return HttpResponse("Hello, home!")

def FrontP(request):
    return HttpResponse("Welcome to the front page")

def greet(request, name):
    return render(request, "hello/greet.html",{
        "name": name
    })

newyear/views.py
from django.shortcuts import render
import datetime

# Create your views here.

def index (request):
    now = datetime.datetime.now()
    return render(request, "newyear/index.html", {
        "newyear": now.month ==1 and now.day == 1
    })

tasks/views.py
from django.shortcuts import render

tasks = ["man","vrouw","dier"]

# Create your views here.
def index(request):
    return render(request, "tasks/index.html",{
        "tasks": tasks
    })

def add(request):
    return render(request, "tasks/add.html",{
        "tasks": tasks
    })

hello/templates/hello/greet.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Hello, {{name}}!</h1>
</body>
</html>

hello/templates/hello/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>

    <H1>Hellloooooo</H1>
    
</body>
</html>

newyear/templates/newyear/index.html
{% load static %}
<!DOCTYPE html>


<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static 'newyear/styles.css' %}" rel="stylesheet">
    <title>Document</title>
</head>
<body>
    

    {%if newyear%}
    <h1>YES</h1>
    {% else %}
    <h1>NO</h1>
    {% endif %}


</body>
</html>

tasks/templates/tasks/add.html
{%extends "tasks/layout.html" %}

{% block body%}

    <form action="{% url 'tasks:add' %}" method="post">
       {% csrf_token %}
       <h1>add task</h1>
       <input type="text">
       <button type="submit">submit</button>
    </form>
    <a href="{% url 'tasks:index' %}">view tasks</a>
{% endblock %}

tasks/templates/tasks/index.html
{%extends "tasks/layout.html" %}

{% block body%}
    <ul>
        {% for task in tasks%}
        <li>{{ task }}</li>
        {% endfor %}
    </ul>

    <a href="{% url 'tasks:add' %}">new task</a>
{% endblock %}

tasks/templates/tasks/layout.html
{% load static %}
<!DOCTYPE html>


<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static 'newyear/styles.css' %}" rel="stylesheet">
    <title>Document</title>
</head>
<body>
    
    {% block body%}
    {%endblock%}

</body>
</html>